"""empty message

Revision ID: 766d86890f9d
Revises: e31755403a65
Create Date: 2024-04-04 15:41:05.123599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d86890f9d'
down_revision = 'e31755403a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('video_uid',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('video_uid',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
