"""empty message

Revision ID: e31755403a65
Revises: b87d705e58fb
Create Date: 2024-04-04 15:22:19.304487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31755403a65'
down_revision = 'b87d705e58fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('video_uid',
               existing_type=sa.VARCHAR(),
               type_=app.models.user.HashedUUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('video_uid',
               existing_type=app.models.user.HashedUUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
